### PR TITLE
Fix template compilation

### LINKED ISSUE #59: Demo and Documentation page uses unexistent video url
This is probably related to 
https://github.com/contently/videojs-annotation-comments/blob/master/docs/_site/index.html#L40
Video source returns 404 😟

### LINKED ISSUE #61: Test page rises a error
Hello, I've been trying to test the plugin in order to better understand how to manage annotations.
I've cloned the repo, and followet the instructions in Readme concerning "Develop and build", but once launched the yarn watch, and opened the browser, looking at the console, the following error is shown.
How to deal with it?

`VIDEOJS: ERROR: TypeError: "Templates[templateName] is not a function"
    renderTemplate player_ui_component.js:70
    render comment.js:38
    Comment comment.js:21
    comments comment_list.js:19
    CommentList comment_list.js:17
    buildComments annotation.js:28
    Annotation annotation.js:19
    _annotations annotation_state.js:34
    set annotation_state.js:34
    postLoadDataConstructor annotation_comments.js:59
    dispatcher video.min.js:12
    le video.min.js:12
    trigger video.min.js:12
    <anonymous> video.min.js:12
    dispatcher video.min.js:12
video.min.js:12:695
    e http://localhost:3004/video.js/dist/video.min.js:12
    error http://localhost:3004/video.js/dist/video.min.js:12
    dispatcher http://localhost:3004/video.js/dist/video.min.js:12
    le http://localhost:3004/video.js/dist/video.min.js:12
    trigger http://localhost:3004/video.js/dist/video.min.js:12
    <anonima> http://localhost:3004/video.js/dist/video.min.js:12
    dispatcher http://localhost:3004/video.js/dist/video.min.js:12`

### LINKED ISSUE #62: ERROR: TypeError: Templates[templateName] is not a function
After gulp build in compiled version and as well as test page, I am getting below error

VIDEOJS: ERROR: TypeError: Templates[templateName] is not a function
    at PlayerButton.renderTemplate (player_ui_component.js:70)
    at PlayerButton.render (player_button.js:29)
    at new PlayerButton (player_button.js:12)
    at new Controls (controls.js:34)
    at AnnotationComments.postLoadDataConstructor (annotation_comments.js:61)
    at HTMLDivElement.data.dispatcher (video.js:1866)
    at trigger (video.js:2002)
    at Player.trigger$1 [as trigger] (video.js:2887)
    at Player.<computed> [as handleTechLoadeddata_] (video.js:28708)
    at HTMLVideoElement.data.dispatcher (video.js:1866)
(anonymous) @ video.js:80
log.error @ video.js:268
data.dispatcher @ video.js:1868
trigger @ video.js:2002
trigger$1 @ video.js:2887
Player.<computed> @ video.js:28708
data.dispatcher @ video.js:1866

Video JS version: 7.6.6
Videojs-annotation-comments: 2.0.1
Node: 10.6.3
NPM: 6.9.0

### PR DESCRIPTION
**Pull request by jackpope**
Fixes #62
Fixes #61 
Fixes #59

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -83,110 +81,97 @@ function compile(watch, cb) {
...
     )
-    .pipe(wrap("Handlebars.template(<%= contents %>)"))
+    .pipe(wrap('Handlebars.template(<%= contents %>)'))
     .pipe(
       declare({
-        root: "exports",
+        root: 'exports',
         noRedeclare: true, // Avoid duplicate declarations
-        processName: function(filePath) {
+        namespace: 'templates',
```
Comment (jackpope) [inline gulpfile.js:129]: Hard coding the namespace to 'templates' here

File: src/js/lib/player_ui_component.js [hunk 2]
```diff
@@ -5,14 +5,10 @@
 
 const Handlebars = require('handlebars/runtime');
 const PlayerComponent = require('./player_component');
-const Templates = require('./../compiled/templates');
-const Utils = require('./../lib/utils');
+const { templates } = require('../compiled/templates');
```
Comment (jackpope) [inline src/js/lib/player_ui_component.js:8]: Deconstructing the new templates namespace here
